package elasticsearch

const allowUnRestrictedIndicesKey = "allow_restricted_indices"
const applicationsKey = "applications"
const clusterKey = "cluster"
const emailKey = "email"
const enabledKey = "enabled"
const expirationKey = "expiration"
const fieldSecurityKey = "field_security"
const fullNameKey = "full_name"
const grantKey = "grant"
const indicesKey = "indices"
const metadataKey = "metadata"
const nameKey = "name"
const namesKey = "names"
const passwordKey = "password"
const privilegesKey = "privileges"
const queryKey = "query"
const resourcesKey = "resources"
const roleDescriptorsKey = "role_descriptors"
const rolesKey = "roles"
const runAsKey = "run_as"
const usernameKey = "username"
const apiKeyKey = "api_key"
